/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6.impl;

import com.github.toerob.inform6.Inform6Package;
import com.github.toerob.inform6.Primary;
import com.github.toerob.inform6.PropertyDeclaration;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Property Declaration</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.impl.PropertyDeclarationImpl#getName <em>Name</em>}</li>
 *   <li>{@link com.github.toerob.inform6.impl.PropertyDeclarationImpl#getAdditive <em>Additive</em>}</li>
 *   <li>{@link com.github.toerob.inform6.impl.PropertyDeclarationImpl#getValue <em>Value</em>}</li>
 *   <li>{@link com.github.toerob.inform6.impl.PropertyDeclarationImpl#getAliasedProperty <em>Aliased Property</em>}</li>
 * </ul>
 *
 * @generated
 */
public class PropertyDeclarationImpl extends DirectiveImpl implements PropertyDeclaration
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getAdditive() <em>Additive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdditive()
   * @generated
   * @ordered
   */
  protected static final String ADDITIVE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getAdditive() <em>Additive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAdditive()
   * @generated
   * @ordered
   */
  protected String additive = ADDITIVE_EDEFAULT;

  /**
   * The cached value of the '{@link #getValue() <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getValue()
   * @generated
   * @ordered
   */
  protected Primary value;

  /**
   * The cached value of the '{@link #getAliasedProperty() <em>Aliased Property</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAliasedProperty()
   * @generated
   * @ordered
   */
  protected Primary aliasedProperty;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PropertyDeclarationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return Inform6Package.Literals.PROPERTY_DECLARATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Inform6Package.PROPERTY_DECLARATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getAdditive()
  {
    return additive;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAdditive(String newAdditive)
  {
    String oldAdditive = additive;
    additive = newAdditive;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Inform6Package.PROPERTY_DECLARATION__ADDITIVE, oldAdditive, additive));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Primary getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetValue(Primary newValue, NotificationChain msgs)
  {
    Primary oldValue = value;
    value = newValue;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Inform6Package.PROPERTY_DECLARATION__VALUE, oldValue, newValue);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setValue(Primary newValue)
  {
    if (newValue != value)
    {
      NotificationChain msgs = null;
      if (value != null)
        msgs = ((InternalEObject)value).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Inform6Package.PROPERTY_DECLARATION__VALUE, null, msgs);
      if (newValue != null)
        msgs = ((InternalEObject)newValue).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Inform6Package.PROPERTY_DECLARATION__VALUE, null, msgs);
      msgs = basicSetValue(newValue, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Inform6Package.PROPERTY_DECLARATION__VALUE, newValue, newValue));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Primary getAliasedProperty()
  {
    return aliasedProperty;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAliasedProperty(Primary newAliasedProperty, NotificationChain msgs)
  {
    Primary oldAliasedProperty = aliasedProperty;
    aliasedProperty = newAliasedProperty;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY, oldAliasedProperty, newAliasedProperty);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAliasedProperty(Primary newAliasedProperty)
  {
    if (newAliasedProperty != aliasedProperty)
    {
      NotificationChain msgs = null;
      if (aliasedProperty != null)
        msgs = ((InternalEObject)aliasedProperty).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY, null, msgs);
      if (newAliasedProperty != null)
        msgs = ((InternalEObject)newAliasedProperty).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY, null, msgs);
      msgs = basicSetAliasedProperty(newAliasedProperty, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY, newAliasedProperty, newAliasedProperty));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case Inform6Package.PROPERTY_DECLARATION__VALUE:
        return basicSetValue(null, msgs);
      case Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY:
        return basicSetAliasedProperty(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case Inform6Package.PROPERTY_DECLARATION__NAME:
        return getName();
      case Inform6Package.PROPERTY_DECLARATION__ADDITIVE:
        return getAdditive();
      case Inform6Package.PROPERTY_DECLARATION__VALUE:
        return getValue();
      case Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY:
        return getAliasedProperty();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case Inform6Package.PROPERTY_DECLARATION__NAME:
        setName((String)newValue);
        return;
      case Inform6Package.PROPERTY_DECLARATION__ADDITIVE:
        setAdditive((String)newValue);
        return;
      case Inform6Package.PROPERTY_DECLARATION__VALUE:
        setValue((Primary)newValue);
        return;
      case Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY:
        setAliasedProperty((Primary)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case Inform6Package.PROPERTY_DECLARATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case Inform6Package.PROPERTY_DECLARATION__ADDITIVE:
        setAdditive(ADDITIVE_EDEFAULT);
        return;
      case Inform6Package.PROPERTY_DECLARATION__VALUE:
        setValue((Primary)null);
        return;
      case Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY:
        setAliasedProperty((Primary)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case Inform6Package.PROPERTY_DECLARATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case Inform6Package.PROPERTY_DECLARATION__ADDITIVE:
        return ADDITIVE_EDEFAULT == null ? additive != null : !ADDITIVE_EDEFAULT.equals(additive);
      case Inform6Package.PROPERTY_DECLARATION__VALUE:
        return value != null;
      case Inform6Package.PROPERTY_DECLARATION__ALIASED_PROPERTY:
        return aliasedProperty != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", additive: ");
    result.append(additive);
    result.append(')');
    return result.toString();
  }

} //PropertyDeclarationImpl
