/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.tests;

import com.github.toerob.inform6.Program;
import com.github.toerob.tests.Inform6InjectorProvider;
import com.google.inject.Inject;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(Inform6InjectorProvider.class)
@SuppressWarnings("all")
public class Inform6ParsingTest {
  @Inject
  private ParseHelper<Program> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Object testObject \"testObject\"");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("with ");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("property1 \"string\",");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("property2 123,");
      _builder.newLine();
      _builder.append("\t\t");
      _builder.append("property3 \'string array element 2\' \'string array element 2\'");
      _builder.newLine();
      _builder.append("\t");
      _builder.append("has light openable;");
      _builder.newLine();
      _builder.newLine();
      final Program result = this.parseHelper.parse(_builder);
      Assertions.assertNotNull(result);
      final EList<Resource.Diagnostic> errors = result.eResource().getErrors();
      boolean _isEmpty = errors.isEmpty();
      StringConcatenation _builder_1 = new StringConcatenation();
      _builder_1.append("Unexpected errors: ");
      String _join = IterableExtensions.join(errors, ", ");
      _builder_1.append(_join);
      Assertions.assertTrue(_isEmpty, _builder_1.toString());
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
