/*
 * generated by Xtext 2.22.0
 */
package com.github.toerob.ide.contentassist.antlr;

import com.github.toerob.ide.contentassist.antlr.internal.InternalInform6Parser;
import com.github.toerob.services.Inform6GrammarAccess;
import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class Inform6Parser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(Inform6GrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, Inform6GrammarAccess grammarAccess) {
			builder.put(grammarAccess.getProgramAccess().getAlternatives(), "rule__Program__Alternatives");
			builder.put(grammarAccess.getDirectiveAccess().getAlternatives(), "rule__Directive__Alternatives");
			builder.put(grammarAccess.getCommentDeclarationAccess().getAlternatives(), "rule__CommentDeclaration__Alternatives");
			builder.put(grammarAccess.getIncludeDeclarationAccess().getAlternatives_0(), "rule__IncludeDeclaration__Alternatives_0");
			builder.put(grammarAccess.getPropertyDirectiveAccess().getNameAlternatives_2_0(), "rule__PropertyDirective__NameAlternatives_2_0");
			builder.put(grammarAccess.getGlobalDeclarationAccess().getNameAlternatives_1_0(), "rule__GlobalDeclaration__NameAlternatives_1_0");
			builder.put(grammarAccess.getAttributeDeclarationAccess().getNameAlternatives_2_0_0(), "rule__AttributeDeclaration__NameAlternatives_2_0_0");
			builder.put(grammarAccess.getAttributeDeclarationAccess().getAliasedAttributeAlternatives_2_1_1_0(), "rule__AttributeDeclaration__AliasedAttributeAlternatives_2_1_1_0");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getAlternatives_1(), "rule__PropertyDeclaration__Alternatives_1");
			builder.put(grammarAccess.getClassDeclarationAccess().getAlternatives_1(), "rule__ClassDeclaration__Alternatives_1");
			builder.put(grammarAccess.getClassDeclarationAccess().getPropertiesAlternatives_4_0(), "rule__ClassDeclaration__PropertiesAlternatives_4_0");
			builder.put(grammarAccess.getClassDeclarationAccess().getPropertiesAlternatives_5_1_0(), "rule__ClassDeclaration__PropertiesAlternatives_5_1_0");
			builder.put(grammarAccess.getObjectDeclarationAccess().getAlternatives_0_1(), "rule__ObjectDeclaration__Alternatives_0_1");
			builder.put(grammarAccess.getObjectDeclarationAccess().getPropertiesAlternatives_0_6_0(), "rule__ObjectDeclaration__PropertiesAlternatives_0_6_0");
			builder.put(grammarAccess.getObjectDeclarationAccess().getPropertiesAlternatives_0_7_1_0(), "rule__ObjectDeclaration__PropertiesAlternatives_0_7_1_0");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getAlternatives_1(), "rule__IdlessObjectDeclaration__Alternatives_1");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getPropertiesAlternatives_5_0(), "rule__IdlessObjectDeclaration__PropertiesAlternatives_5_0");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getPropertiesAlternatives_6_1_0(), "rule__IdlessObjectDeclaration__PropertiesAlternatives_6_1_0");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getPropertiesAlternatives_5_0(), "rule__NearbyDeclaration__PropertiesAlternatives_5_0");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getPropertiesAlternatives_6_1_0(), "rule__NearbyDeclaration__PropertiesAlternatives_6_1_0");
			builder.put(grammarAccess.getVerbDeclarationAccess().getAlternatives(), "rule__VerbDeclaration__Alternatives");
			builder.put(grammarAccess.getVerbDeclarationAccess().getAlternatives_1_4(), "rule__VerbDeclaration__Alternatives_1_4");
			builder.put(grammarAccess.getVerbAssignmentAccess().getAlternatives(), "rule__VerbAssignment__Alternatives");
			builder.put(grammarAccess.getArrayDeclarationAccess().getNameAlternatives_1_0(), "rule__ArrayDeclaration__NameAlternatives_1_0");
			builder.put(grammarAccess.getArrayTypeAccess().getAlternatives(), "rule__ArrayType__Alternatives");
			builder.put(grammarAccess.getArrayTypeAccess().getTypeAlternatives_2_1_0(), "rule__ArrayType__TypeAlternatives_2_1_0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getOperatorAlternatives_0_1_0(), "rule__PrimaryExpression__OperatorAlternatives_0_1_0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getOperatorAlternatives_1_2_0(), "rule__PrimaryExpression__OperatorAlternatives_1_2_0");
			builder.put(grammarAccess.getPropertySectionAccess().getAlternatives_0(), "rule__PropertySection__Alternatives_0");
			builder.put(grammarAccess.getPropertySectionAccess().getNameAlternatives_0_0_1_0(), "rule__PropertySection__NameAlternatives_0_0_1_0");
			builder.put(grammarAccess.getPropertyAccess().getAlternatives(), "rule__Property__Alternatives");
			builder.put(grammarAccess.getPropertyAccess().getAlternatives_0_2(), "rule__Property__Alternatives_0_2");
			builder.put(grammarAccess.getPropertyAccess().getAlternatives_1_2(), "rule__Property__Alternatives_1_2");
			builder.put(grammarAccess.getPropertyAccess().getAlternatives_2_2(), "rule__Property__Alternatives_2_2");
			builder.put(grammarAccess.getFuzzyExpressionAccess().getAlternatives(), "rule__FuzzyExpression__Alternatives");
			builder.put(grammarAccess.getExpressionAccess().getAlternatives_0(), "rule__Expression__Alternatives_0");
			builder.put(grammarAccess.getPrimaryAccess().getAlternatives(), "rule__Primary__Alternatives");
			builder.put(grammarAccess.getAttributeAccess().getAlternatives_2(), "rule__Attribute__Alternatives_2");
			builder.put(grammarAccess.getDirectiveAccess().getGroup_20(), "rule__Directive__Group_20__0");
			builder.put(grammarAccess.getDirectiveAccess().getGroup_21(), "rule__Directive__Group_21__0");
			builder.put(grammarAccess.getDirectiveAccess().getGroup_22(), "rule__Directive__Group_22__0");
			builder.put(grammarAccess.getDirectiveAccess().getGroup_23(), "rule__Directive__Group_23__0");
			builder.put(grammarAccess.getDirectiveAccess().getGroup_24(), "rule__Directive__Group_24__0");
			builder.put(grammarAccess.getDirectiveAccess().getGroup_25(), "rule__Directive__Group_25__0");
			builder.put(grammarAccess.getDirectiveAccess().getGroup_26(), "rule__Directive__Group_26__0");
			builder.put(grammarAccess.getSystemFileDirectiveAccess().getGroup(), "rule__SystemFileDirective__Group__0");
			builder.put(grammarAccess.getFakeActionDirectiveAccess().getGroup(), "rule__FakeActionDirective__Group__0");
			builder.put(grammarAccess.getAbbreviateDirectiveAccess().getGroup(), "rule__AbbreviateDirective__Group__0");
			builder.put(grammarAccess.getAbortDirectiveAccess().getGroup(), "rule__AbortDirective__Group__0");
			builder.put(grammarAccess.getMessageDirectiveAccess().getGroup(), "rule__MessageDirective__Group__0");
			builder.put(grammarAccess.getZcharacterDirectiveAccess().getGroup(), "rule__ZcharacterDirective__Group__0");
			builder.put(grammarAccess.getCommentDeclarationAccess().getGroup_1(), "rule__CommentDeclaration__Group_1__0");
			builder.put(grammarAccess.getIncludeDeclarationAccess().getGroup(), "rule__IncludeDeclaration__Group__0");
			builder.put(grammarAccess.getEndDirectiveAccess().getGroup(), "rule__EndDirective__Group__0");
			builder.put(grammarAccess.getPropertyDirectiveAccess().getGroup(), "rule__PropertyDirective__Group__0");
			builder.put(grammarAccess.getLowStringDirectiveAccess().getGroup(), "rule__LowStringDirective__Group__0");
			builder.put(grammarAccess.getReleaseDirectiveAccess().getGroup(), "rule__ReleaseDirective__Group__0");
			builder.put(grammarAccess.getReplaceDirectiveAccess().getGroup(), "rule__ReplaceDirective__Group__0");
			builder.put(grammarAccess.getSerialDirectiveAccess().getGroup(), "rule__SerialDirective__Group__0");
			builder.put(grammarAccess.getGlobalConstantDeclarationAccess().getGroup(), "rule__GlobalConstantDeclaration__Group__0");
			builder.put(grammarAccess.getGlobalDefaultDeclarationAccess().getGroup(), "rule__GlobalDefaultDeclaration__Group__0");
			builder.put(grammarAccess.getSwitchesDeclarationAccess().getGroup(), "rule__SwitchesDeclaration__Group__0");
			builder.put(grammarAccess.getGlobalDeclarationAccess().getGroup(), "rule__GlobalDeclaration__Group__0");
			builder.put(grammarAccess.getGlobalDeclarationAccess().getGroup_2(), "rule__GlobalDeclaration__Group_2__0");
			builder.put(grammarAccess.getAttributeDeclarationAccess().getGroup(), "rule__AttributeDeclaration__Group__0");
			builder.put(grammarAccess.getAttributeDeclarationAccess().getGroup_2(), "rule__AttributeDeclaration__Group_2__0");
			builder.put(grammarAccess.getAttributeDeclarationAccess().getGroup_2_1(), "rule__AttributeDeclaration__Group_2_1__0");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getGroup(), "rule__PropertyDeclaration__Group__0");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getGroup_1_0(), "rule__PropertyDeclaration__Group_1_0__0");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getGroup_1_1(), "rule__PropertyDeclaration__Group_1_1__0");
			builder.put(grammarAccess.getClassDeclarationAccess().getGroup(), "rule__ClassDeclaration__Group__0");
			builder.put(grammarAccess.getClassDeclarationAccess().getGroup_3(), "rule__ClassDeclaration__Group_3__0");
			builder.put(grammarAccess.getClassDeclarationAccess().getGroup_5(), "rule__ClassDeclaration__Group_5__0");
			builder.put(grammarAccess.getObjectDeclarationAccess().getGroup(), "rule__ObjectDeclaration__Group__0");
			builder.put(grammarAccess.getObjectDeclarationAccess().getGroup_0(), "rule__ObjectDeclaration__Group_0__0");
			builder.put(grammarAccess.getObjectDeclarationAccess().getGroup_0_7(), "rule__ObjectDeclaration__Group_0_7__0");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getGroup(), "rule__IdlessObjectDeclaration__Group__0");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getGroup_6(), "rule__IdlessObjectDeclaration__Group_6__0");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getGroup(), "rule__NearbyDeclaration__Group__0");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getGroup_6(), "rule__NearbyDeclaration__Group_6__0");
			builder.put(grammarAccess.getVerbDeclarationAccess().getGroup_0(), "rule__VerbDeclaration__Group_0__0");
			builder.put(grammarAccess.getVerbDeclarationAccess().getGroup_1(), "rule__VerbDeclaration__Group_1__0");
			builder.put(grammarAccess.getVerbBodyAccess().getGroup(), "rule__VerbBody__Group__0");
			builder.put(grammarAccess.getVerbAssignmentAccess().getGroup_1(), "rule__VerbAssignment__Group_1__0");
			builder.put(grammarAccess.getVerbAssignmentAccess().getGroup_2(), "rule__VerbAssignment__Group_2__0");
			builder.put(grammarAccess.getVerbAssignmentAccess().getGroup_2_2(), "rule__VerbAssignment__Group_2_2__0");
			builder.put(grammarAccess.getArrayDeclarationAccess().getGroup(), "rule__ArrayDeclaration__Group__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup_0(), "rule__ArrayType__Group_0__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup_1(), "rule__ArrayType__Group_1__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup_2(), "rule__ArrayType__Group_2__0");
			builder.put(grammarAccess.getArrayTypeAccess().getGroup_3(), "rule__ArrayType__Group_3__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_0(), "rule__PrimaryExpression__Group_0__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_1(), "rule__PrimaryExpression__Group_1__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_2(), "rule__PrimaryExpression__Group_2__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_4(), "rule__PrimaryExpression__Group_4__0");
			builder.put(grammarAccess.getClassSectionAccess().getGroup(), "rule__ClassSection__Group__0");
			builder.put(grammarAccess.getPropertySectionAccess().getGroup(), "rule__PropertySection__Group__0");
			builder.put(grammarAccess.getPropertySectionAccess().getGroup_0_0(), "rule__PropertySection__Group_0_0__0");
			builder.put(grammarAccess.getPropertySectionAccess().getGroup_0_0_3(), "rule__PropertySection__Group_0_0_3__0");
			builder.put(grammarAccess.getPropertySectionAccess().getGroup_0_1(), "rule__PropertySection__Group_0_1__0");
			builder.put(grammarAccess.getAttributeSectionAccess().getGroup(), "rule__AttributeSection__Group__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_0(), "rule__Property__Group_0__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_1(), "rule__Property__Group_1__0");
			builder.put(grammarAccess.getPropertyAccess().getGroup_2(), "rule__Property__Group_2__0");
			builder.put(grammarAccess.getAbstractArrayAccess().getGroup(), "rule__AbstractArray__Group__0");
			builder.put(grammarAccess.getAbstractArrayAccess().getGroup_1(), "rule__AbstractArray__Group_1__0");
			builder.put(grammarAccess.getMethodAccess().getGroup(), "rule__Method__Group__0");
			builder.put(grammarAccess.getGlobalFunctionDefinitionAccess().getGroup(), "rule__GlobalFunctionDefinition__Group__0");
			builder.put(grammarAccess.getFunctionHeaderAccess().getGroup(), "rule__FunctionHeader__Group__0");
			builder.put(grammarAccess.getExpressionAccess().getGroup(), "rule__Expression__Group__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_0(), "rule__Primary__Group_0__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_2(), "rule__Primary__Group_2__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_3(), "rule__Primary__Group_3__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_4(), "rule__Primary__Group_4__0");
			builder.put(grammarAccess.getPrimaryAccess().getGroup_5(), "rule__Primary__Group_5__0");
			builder.put(grammarAccess.getNumberAccess().getGroup(), "rule__Number__Group__0");
			builder.put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
			builder.put(grammarAccess.getProgramAccess().getDirectivesAssignment_0(), "rule__Program__DirectivesAssignment_0");
			builder.put(grammarAccess.getProgramAccess().getImportsAssignment_1(), "rule__Program__ImportsAssignment_1");
			builder.put(grammarAccess.getMessageDirectiveAccess().getNameAssignment_1(), "rule__MessageDirective__NameAssignment_1");
			builder.put(grammarAccess.getMessageDirectiveAccess().getStringAssignment_2(), "rule__MessageDirective__StringAssignment_2");
			builder.put(grammarAccess.getZcharacterDirectiveAccess().getStringAssignment_1(), "rule__ZcharacterDirective__StringAssignment_1");
			builder.put(grammarAccess.getCompilerDirectiveAccess().getValueAssignment(), "rule__CompilerDirective__ValueAssignment");
			builder.put(grammarAccess.getIncludeDeclarationAccess().getImportURIAssignment_1(), "rule__IncludeDeclaration__ImportURIAssignment_1");
			builder.put(grammarAccess.getPropertyDirectiveAccess().getAdditiveAssignment_1(), "rule__PropertyDirective__AdditiveAssignment_1");
			builder.put(grammarAccess.getPropertyDirectiveAccess().getNameAssignment_2(), "rule__PropertyDirective__NameAssignment_2");
			builder.put(grammarAccess.getPropertyDirectiveAccess().getValueAssignment_3(), "rule__PropertyDirective__ValueAssignment_3");
			builder.put(grammarAccess.getReleaseDirectiveAccess().getNameAssignment_0(), "rule__ReleaseDirective__NameAssignment_0");
			builder.put(grammarAccess.getReleaseDirectiveAccess().getVersionAssignment_1(), "rule__ReleaseDirective__VersionAssignment_1");
			builder.put(grammarAccess.getReplaceDirectiveAccess().getNameAssignment_0(), "rule__ReplaceDirective__NameAssignment_0");
			builder.put(grammarAccess.getReplaceDirectiveAccess().getIdAssignment_1(), "rule__ReplaceDirective__IdAssignment_1");
			builder.put(grammarAccess.getSerialDirectiveAccess().getNameAssignment_0(), "rule__SerialDirective__NameAssignment_0");
			builder.put(grammarAccess.getSerialDirectiveAccess().getSerialAssignment_1(), "rule__SerialDirective__SerialAssignment_1");
			builder.put(grammarAccess.getGlobalConstantDeclarationAccess().getNameAssignment_1(), "rule__GlobalConstantDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getGlobalConstantDeclarationAccess().getValueAssignment_3(), "rule__GlobalConstantDeclaration__ValueAssignment_3");
			builder.put(grammarAccess.getGlobalDefaultDeclarationAccess().getNameAssignment_1(), "rule__GlobalDefaultDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getGlobalDefaultDeclarationAccess().getValueAssignment_3(), "rule__GlobalDefaultDeclaration__ValueAssignment_3");
			builder.put(grammarAccess.getSwitchesDeclarationAccess().getNameAssignment_0(), "rule__SwitchesDeclaration__NameAssignment_0");
			builder.put(grammarAccess.getSwitchesDeclarationAccess().getSwitchesAssignment_1(), "rule__SwitchesDeclaration__SwitchesAssignment_1");
			builder.put(grammarAccess.getGlobalDeclarationAccess().getNameAssignment_1(), "rule__GlobalDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getGlobalDeclarationAccess().getValueAssignment_2_1(), "rule__GlobalDeclaration__ValueAssignment_2_1");
			builder.put(grammarAccess.getGlobalConstantValueAccess().getNameAssignment(), "rule__GlobalConstantValue__NameAssignment");
			builder.put(grammarAccess.getAttributeDeclarationAccess().getNameAssignment_2_0(), "rule__AttributeDeclaration__NameAssignment_2_0");
			builder.put(grammarAccess.getAttributeDeclarationAccess().getAliasedAttributeAssignment_2_1_1(), "rule__AttributeDeclaration__AliasedAttributeAssignment_2_1_1");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getNameAssignment_1_0_0(), "rule__PropertyDeclaration__NameAssignment_1_0_0");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getAdditiveAssignment_1_0_1(), "rule__PropertyDeclaration__AdditiveAssignment_1_0_1");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getValueAssignment_1_0_2(), "rule__PropertyDeclaration__ValueAssignment_1_0_2");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getNameAssignment_1_1_0(), "rule__PropertyDeclaration__NameAssignment_1_1_0");
			builder.put(grammarAccess.getPropertyDeclarationAccess().getAliasedPropertyAssignment_1_1_2(), "rule__PropertyDeclaration__AliasedPropertyAssignment_1_1_2");
			builder.put(grammarAccess.getClassDeclarationAccess().getNameAssignment_2(), "rule__ClassDeclaration__NameAssignment_2");
			builder.put(grammarAccess.getClassDeclarationAccess().getCardinalityAssignment_3_0(), "rule__ClassDeclaration__CardinalityAssignment_3_0");
			builder.put(grammarAccess.getClassDeclarationAccess().getMaxAssignment_3_1(), "rule__ClassDeclaration__MaxAssignment_3_1");
			builder.put(grammarAccess.getClassDeclarationAccess().getPropertiesAssignment_4(), "rule__ClassDeclaration__PropertiesAssignment_4");
			builder.put(grammarAccess.getClassDeclarationAccess().getPropertiesAssignment_5_1(), "rule__ClassDeclaration__PropertiesAssignment_5_1");
			builder.put(grammarAccess.getObjectDeclarationAccess().getObjectAssignment_0_1_0(), "rule__ObjectDeclaration__ObjectAssignment_0_1_0");
			builder.put(grammarAccess.getObjectDeclarationAccess().getSuperTypeAssignment_0_1_1(), "rule__ObjectDeclaration__SuperTypeAssignment_0_1_1");
			builder.put(grammarAccess.getObjectDeclarationAccess().getLevelAssignment_0_2(), "rule__ObjectDeclaration__LevelAssignment_0_2");
			builder.put(grammarAccess.getObjectDeclarationAccess().getNameAssignment_0_3(), "rule__ObjectDeclaration__NameAssignment_0_3");
			builder.put(grammarAccess.getObjectDeclarationAccess().getHeadlineAssignment_0_4(), "rule__ObjectDeclaration__HeadlineAssignment_0_4");
			builder.put(grammarAccess.getObjectDeclarationAccess().getInAssignment_0_5(), "rule__ObjectDeclaration__InAssignment_0_5");
			builder.put(grammarAccess.getObjectDeclarationAccess().getPropertiesAssignment_0_6(), "rule__ObjectDeclaration__PropertiesAssignment_0_6");
			builder.put(grammarAccess.getObjectDeclarationAccess().getPropertiesAssignment_0_7_1(), "rule__ObjectDeclaration__PropertiesAssignment_0_7_1");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getObjectAssignment_1_0(), "rule__IdlessObjectDeclaration__ObjectAssignment_1_0");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getSuperTypeAssignment_1_1(), "rule__IdlessObjectDeclaration__SuperTypeAssignment_1_1");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getLevelAssignment_2(), "rule__IdlessObjectDeclaration__LevelAssignment_2");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getNameAssignment_3(), "rule__IdlessObjectDeclaration__NameAssignment_3");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getInAssignment_4(), "rule__IdlessObjectDeclaration__InAssignment_4");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getPropertiesAssignment_5(), "rule__IdlessObjectDeclaration__PropertiesAssignment_5");
			builder.put(grammarAccess.getIdlessObjectDeclarationAccess().getPropertiesAssignment_6_1(), "rule__IdlessObjectDeclaration__PropertiesAssignment_6_1");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getNameAssignment_2(), "rule__NearbyDeclaration__NameAssignment_2");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getHeadlineAssignment_3(), "rule__NearbyDeclaration__HeadlineAssignment_3");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getInAssignment_4(), "rule__NearbyDeclaration__InAssignment_4");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getPropertiesAssignment_5(), "rule__NearbyDeclaration__PropertiesAssignment_5");
			builder.put(grammarAccess.getNearbyDeclarationAccess().getPropertiesAssignment_6_1(), "rule__NearbyDeclaration__PropertiesAssignment_6_1");
			builder.put(grammarAccess.getVerbDeclarationAccess().getNameAssignment_0_1(), "rule__VerbDeclaration__NameAssignment_0_1");
			builder.put(grammarAccess.getVerbDeclarationAccess().getMetaAssignment_0_2(), "rule__VerbDeclaration__MetaAssignment_0_2");
			builder.put(grammarAccess.getVerbDeclarationAccess().getSynAssignment_0_3(), "rule__VerbDeclaration__SynAssignment_0_3");
			builder.put(grammarAccess.getVerbDeclarationAccess().getDefintionsAssignment_0_4(), "rule__VerbDeclaration__DefintionsAssignment_0_4");
			builder.put(grammarAccess.getVerbDeclarationAccess().getNameAssignment_1_1(), "rule__VerbDeclaration__NameAssignment_1_1");
			builder.put(grammarAccess.getVerbDeclarationAccess().getOnlyAssignment_1_2(), "rule__VerbDeclaration__OnlyAssignment_1_2");
			builder.put(grammarAccess.getVerbDeclarationAccess().getSynAssignment_1_3(), "rule__VerbDeclaration__SynAssignment_1_3");
			builder.put(grammarAccess.getVerbDeclarationAccess().getDefintionsAssignment_1_5(), "rule__VerbDeclaration__DefintionsAssignment_1_5");
			builder.put(grammarAccess.getVerbBodyAccess().getDefinitionsAssignment_1(), "rule__VerbBody__DefinitionsAssignment_1");
			builder.put(grammarAccess.getVerbBodyAccess().getNameAssignment_3(), "rule__VerbBody__NameAssignment_3");
			builder.put(grammarAccess.getVerbBodyAccess().getReverseAssignment_4(), "rule__VerbBody__ReverseAssignment_4");
			builder.put(grammarAccess.getArrayDeclarationAccess().getNameAssignment_1(), "rule__ArrayDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getArrayDeclarationAccess().getArrayBodyAssignment_3(), "rule__ArrayDeclaration__ArrayBodyAssignment_3");
			builder.put(grammarAccess.getArrayTypeAccess().getTypeAssignment_0_1(), "rule__ArrayType__TypeAssignment_0_1");
			builder.put(grammarAccess.getArrayTypeAccess().getSizeAssignment_0_2(), "rule__ArrayType__SizeAssignment_0_2");
			builder.put(grammarAccess.getArrayTypeAccess().getContentAssignment_0_3(), "rule__ArrayType__ContentAssignment_0_3");
			builder.put(grammarAccess.getArrayTypeAccess().getTypeAssignment_1_1(), "rule__ArrayType__TypeAssignment_1_1");
			builder.put(grammarAccess.getArrayTypeAccess().getSizeAssignment_1_2(), "rule__ArrayType__SizeAssignment_1_2");
			builder.put(grammarAccess.getArrayTypeAccess().getContentAssignment_1_3(), "rule__ArrayType__ContentAssignment_1_3");
			builder.put(grammarAccess.getArrayTypeAccess().getTypeAssignment_2_1(), "rule__ArrayType__TypeAssignment_2_1");
			builder.put(grammarAccess.getArrayTypeAccess().getSizeAssignment_2_2(), "rule__ArrayType__SizeAssignment_2_2");
			builder.put(grammarAccess.getArrayTypeAccess().getContentAssignment_2_3(), "rule__ArrayType__ContentAssignment_2_3");
			builder.put(grammarAccess.getArrayTypeAccess().getTypeAssignment_3_1(), "rule__ArrayType__TypeAssignment_3_1");
			builder.put(grammarAccess.getArrayTypeAccess().getSizeAssignment_3_2(), "rule__ArrayType__SizeAssignment_3_2");
			builder.put(grammarAccess.getArrayTypeAccess().getContentAssignment_3_3(), "rule__ArrayType__ContentAssignment_3_3");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getLeftAssignment_0_0(), "rule__PrimaryExpression__LeftAssignment_0_0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getOperatorAssignment_0_1(), "rule__PrimaryExpression__OperatorAssignment_0_1");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getRightAssignment_0_2(), "rule__PrimaryExpression__RightAssignment_0_2");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getLeftAssignment_1_1(), "rule__PrimaryExpression__LeftAssignment_1_1");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getOperatorAssignment_1_2(), "rule__PrimaryExpression__OperatorAssignment_1_2");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getRightAssignment_1_3(), "rule__PrimaryExpression__RightAssignment_1_3");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getLeftAssignment_2_1(), "rule__PrimaryExpression__LeftAssignment_2_1");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getLeftAssignment_3(), "rule__PrimaryExpression__LeftAssignment_3");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getUnparsedTokensAssignment_4_2(), "rule__PrimaryExpression__UnparsedTokensAssignment_4_2");
			builder.put(grammarAccess.getClassSectionAccess().getNameAssignment_1(), "rule__ClassSection__NameAssignment_1");
			builder.put(grammarAccess.getClassSectionAccess().getClassPropertyAssignment_2(), "rule__ClassSection__ClassPropertyAssignment_2");
			builder.put(grammarAccess.getPropertySectionAccess().getNameAssignment_0_0_1(), "rule__PropertySection__NameAssignment_0_0_1");
			builder.put(grammarAccess.getPropertySectionAccess().getPropertiesAssignment_0_0_2(), "rule__PropertySection__PropertiesAssignment_0_0_2");
			builder.put(grammarAccess.getPropertySectionAccess().getPropertiesAssignment_0_0_3_1(), "rule__PropertySection__PropertiesAssignment_0_0_3_1");
			builder.put(grammarAccess.getAttributeSectionAccess().getNameAssignment_1(), "rule__AttributeSection__NameAssignment_1");
			builder.put(grammarAccess.getAttributeSectionAccess().getAttributesAssignment_2(), "rule__AttributeSection__AttributesAssignment_2");
			builder.put(grammarAccess.getAttributeSectionAccess().getAttributesAssignment_3(), "rule__AttributeSection__AttributesAssignment_3");
			builder.put(grammarAccess.getPropertyAccess().getNameAssignment_0_1(), "rule__Property__NameAssignment_0_1");
			builder.put(grammarAccess.getPropertyAccess().getMethodAssignment_0_2_0(), "rule__Property__MethodAssignment_0_2_0");
			builder.put(grammarAccess.getPropertyAccess().getArrayAssignment_0_2_1(), "rule__Property__ArrayAssignment_0_2_1");
			builder.put(grammarAccess.getPropertyAccess().getNameAssignment_1_1(), "rule__Property__NameAssignment_1_1");
			builder.put(grammarAccess.getPropertyAccess().getObjectReferenceAssignment_1_2_0(), "rule__Property__ObjectReferenceAssignment_1_2_0");
			builder.put(grammarAccess.getPropertyAccess().getValueAssignment_1_2_1(), "rule__Property__ValueAssignment_1_2_1");
			builder.put(grammarAccess.getPropertyAccess().getMethodAssignment_1_2_2(), "rule__Property__MethodAssignment_1_2_2");
			builder.put(grammarAccess.getPropertyAccess().getArrayAssignment_1_2_3(), "rule__Property__ArrayAssignment_1_2_3");
			builder.put(grammarAccess.getPropertyAccess().getObjectReferencesAssignment_2_2_0(), "rule__Property__ObjectReferencesAssignment_2_2_0");
			builder.put(grammarAccess.getPropertyAccess().getMethodAssignment_2_2_1(), "rule__Property__MethodAssignment_2_2_1");
			builder.put(grammarAccess.getPropertyAccess().getValueAssignment_2_2_2(), "rule__Property__ValueAssignment_2_2_2");
			builder.put(grammarAccess.getAbstractArrayAccess().getArrayAssignment_1_0(), "rule__AbstractArray__ArrayAssignment_1_0");
			builder.put(grammarAccess.getAbstractArrayAccess().getArrayAssignment_1_1(), "rule__AbstractArray__ArrayAssignment_1_1");
			builder.put(grammarAccess.getMethodAccess().getFunctionBodyAssignment_1(), "rule__Method__FunctionBodyAssignment_1");
			builder.put(grammarAccess.getGlobalFunctionDefinitionAccess().getFunctionHeaderAssignment_1(), "rule__GlobalFunctionDefinition__FunctionHeaderAssignment_1");
			builder.put(grammarAccess.getGlobalFunctionDefinitionAccess().getFunctionBodyAssignment_2(), "rule__GlobalFunctionDefinition__FunctionBodyAssignment_2");
			builder.put(grammarAccess.getFunctionHeaderAccess().getVariablesAssignment_1(), "rule__FunctionHeader__VariablesAssignment_1");
			builder.put(grammarAccess.getPrimaryAccess().getIdAssignment_0_1(), "rule__Primary__IdAssignment_0_1");
			builder.put(grammarAccess.getPrimaryAccess().getNumberAssignment_1(), "rule__Primary__NumberAssignment_1");
			builder.put(grammarAccess.getPrimaryAccess().getStringAssignment_2_1(), "rule__Primary__StringAssignment_2_1");
			builder.put(grammarAccess.getPrimaryAccess().getDirectionAssignment_3_1(), "rule__Primary__DirectionAssignment_3_1");
			builder.put(grammarAccess.getPrimaryAccess().getHexAssignment_4_1(), "rule__Primary__HexAssignment_4_1");
			builder.put(grammarAccess.getPrimaryAccess().getBinaryAssignment_5_1(), "rule__Primary__BinaryAssignment_5_1");
			builder.put(grammarAccess.getNumberAccess().getNegativeAssignment_1(), "rule__Number__NegativeAssignment_1");
			builder.put(grammarAccess.getNumberAccess().getValueAssignment_2(), "rule__Number__ValueAssignment_2");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_2_0(), "rule__Attribute__NameAssignment_2_0");
			builder.put(grammarAccess.getAttributeAccess().getNameAssignment_2_1(), "rule__Attribute__NameAssignment_2_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private Inform6GrammarAccess grammarAccess;

	@Override
	protected InternalInform6Parser createParser() {
		InternalInform6Parser result = new InternalInform6Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public Inform6GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(Inform6GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
