/*
 * generated by Xtext 2.24.0
 */
package com.github.toerob.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class Inform6AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("com/github/toerob/parser/antlr/internal/InternalInform6Parser.tokens");
	}
}
