/*
 * generated by Xtext 2.22.0
 */
package com.github.toerob.ide;

import com.github.toerob.Inform6RuntimeModule;
import com.github.toerob.Inform6StandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class Inform6IdeSetup extends Inform6StandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new Inform6RuntimeModule(), new Inform6IdeModule()));
	}
	
}
