/*
 * generated by Xtext 2.22.0
 */
package com.github.toerob.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class Inform6ProposalProvider extends AbstractInform6ProposalProvider {
}
