/*
 * generated by Xtext 2.22.0
 */
package com.github.toerob.scoping;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EReference;
import org.eclipse.xtext.scoping.IScope;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class Inform6ScopeProvider extends AbstractInform6ScopeProvider {

	@Override
	public IScope getScope(EObject context, EReference reference) {
		
		return super.getScope(context, reference);
	}
}
