/**
 * generated by Xtext 2.24.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.Attribute#getName <em>Name</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getAttribute()
 * @model
 * @generated
 */
public interface Attribute extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' reference.
   * @see #setName(AttributeDeclaration)
   * @see com.github.toerob.inform6.Inform6Package#getAttribute_Name()
   * @model
   * @generated
   */
  AttributeDeclaration getName();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.Attribute#getName <em>Name</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' reference.
   * @see #getName()
   * @generated
   */
  void setName(AttributeDeclaration value);

} // Attribute
