/**
 * generated by Xtext 2.24.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.Expression#getLeft <em>Left</em>}</li>
 *   <li>{@link com.github.toerob.inform6.Expression#getOperator <em>Operator</em>}</li>
 *   <li>{@link com.github.toerob.inform6.Expression#getRight <em>Right</em>}</li>
 *   <li>{@link com.github.toerob.inform6.Expression#getUnparsedTokens <em>Unparsed Tokens</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getExpression()
 * @model
 * @generated
 */
public interface Expression extends EObject
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(Primary)
   * @see com.github.toerob.inform6.Inform6Package#getExpression_Left()
   * @model containment="true"
   * @generated
   */
  Primary getLeft();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.Expression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(Primary value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see com.github.toerob.inform6.Inform6Package#getExpression_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.Expression#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(Primary)
   * @see com.github.toerob.inform6.Inform6Package#getExpression_Right()
   * @model containment="true"
   * @generated
   */
  Primary getRight();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.Expression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(Primary value);

  /**
   * Returns the value of the '<em><b>Unparsed Tokens</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unparsed Tokens</em>' attribute list.
   * @see com.github.toerob.inform6.Inform6Package#getExpression_UnparsedTokens()
   * @model unique="false"
   * @generated
   */
  EList<String> getUnparsedTokens();

} // Expression
