/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.FunctionBody#getAnyToken <em>Any Token</em>}</li>
 *   <li>{@link com.github.toerob.inform6.FunctionBody#getSemicolon <em>Semicolon</em>}</li>
 *   <li>{@link com.github.toerob.inform6.FunctionBody#getUnparsed <em>Unparsed</em>}</li>
 *   <li>{@link com.github.toerob.inform6.FunctionBody#getToken <em>Token</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getFunctionBody()
 * @model
 * @generated
 */
public interface FunctionBody extends AnyToken
{
  /**
   * Returns the value of the '<em><b>Any Token</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Any Token</em>' containment reference.
   * @see #setAnyToken(AnyToken)
   * @see com.github.toerob.inform6.Inform6Package#getFunctionBody_AnyToken()
   * @model containment="true"
   * @generated
   */
  AnyToken getAnyToken();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.FunctionBody#getAnyToken <em>Any Token</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Any Token</em>' containment reference.
   * @see #getAnyToken()
   * @generated
   */
  void setAnyToken(AnyToken value);

  /**
   * Returns the value of the '<em><b>Semicolon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semicolon</em>' attribute.
   * @see #setSemicolon(String)
   * @see com.github.toerob.inform6.Inform6Package#getFunctionBody_Semicolon()
   * @model
   * @generated
   */
  String getSemicolon();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.FunctionBody#getSemicolon <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semicolon</em>' attribute.
   * @see #getSemicolon()
   * @generated
   */
  void setSemicolon(String value);

  /**
   * Returns the value of the '<em><b>Unparsed</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unparsed</em>' containment reference.
   * @see #setUnparsed(FunctionBody)
   * @see com.github.toerob.inform6.Inform6Package#getFunctionBody_Unparsed()
   * @model containment="true"
   * @generated
   */
  FunctionBody getUnparsed();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.FunctionBody#getUnparsed <em>Unparsed</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unparsed</em>' containment reference.
   * @see #getUnparsed()
   * @generated
   */
  void setUnparsed(FunctionBody value);

  /**
   * Returns the value of the '<em><b>Token</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Token</em>' attribute.
   * @see #setToken(String)
   * @see com.github.toerob.inform6.Inform6Package#getFunctionBody_Token()
   * @model
   * @generated
   */
  String getToken();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.FunctionBody#getToken <em>Token</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Token</em>' attribute.
   * @see #getToken()
   * @generated
   */
  void setToken(String value);

} // FunctionBody
