/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Global Constant Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.GlobalConstantDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.github.toerob.inform6.GlobalConstantDeclaration#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getGlobalConstantDeclaration()
 * @model
 * @generated
 */
public interface GlobalConstantDeclaration extends Directive
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.github.toerob.inform6.Inform6Package#getGlobalConstantDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.GlobalConstantDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(GlobalConstantValue)
   * @see com.github.toerob.inform6.Inform6Package#getGlobalConstantDeclaration_Value()
   * @model containment="true"
   * @generated
   */
  GlobalConstantValue getValue();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.GlobalConstantDeclaration#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(GlobalConstantValue value);

} // GlobalConstantDeclaration
