/**
 * generated by Xtext 2.24.0
 */
package com.github.toerob.inform6;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Idless Object Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.github.toerob.inform6.Inform6Package#getIdlessObjectDeclaration()
 * @model
 * @generated
 */
public interface IdlessObjectDeclaration extends Directive
{
} // IdlessObjectDeclaration
