/**
 * generated by Xtext 2.24.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Object Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.ObjectDeclaration#getObject <em>Object</em>}</li>
 *   <li>{@link com.github.toerob.inform6.ObjectDeclaration#getSuperType <em>Super Type</em>}</li>
 *   <li>{@link com.github.toerob.inform6.ObjectDeclaration#getLevel <em>Level</em>}</li>
 *   <li>{@link com.github.toerob.inform6.ObjectDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.github.toerob.inform6.ObjectDeclaration#getHeadline <em>Headline</em>}</li>
 *   <li>{@link com.github.toerob.inform6.ObjectDeclaration#getIn <em>In</em>}</li>
 *   <li>{@link com.github.toerob.inform6.ObjectDeclaration#getProperties <em>Properties</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getObjectDeclaration()
 * @model
 * @generated
 */
public interface ObjectDeclaration extends Directive, IdlessObjectDeclaration, NearbyDeclaration
{
  /**
   * Returns the value of the '<em><b>Object</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Object</em>' attribute.
   * @see #setObject(String)
   * @see com.github.toerob.inform6.Inform6Package#getObjectDeclaration_Object()
   * @model
   * @generated
   */
  String getObject();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.ObjectDeclaration#getObject <em>Object</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Object</em>' attribute.
   * @see #getObject()
   * @generated
   */
  void setObject(String value);

  /**
   * Returns the value of the '<em><b>Super Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Super Type</em>' reference.
   * @see #setSuperType(ClassDeclaration)
   * @see com.github.toerob.inform6.Inform6Package#getObjectDeclaration_SuperType()
   * @model
   * @generated
   */
  ClassDeclaration getSuperType();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.ObjectDeclaration#getSuperType <em>Super Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Super Type</em>' reference.
   * @see #getSuperType()
   * @generated
   */
  void setSuperType(ClassDeclaration value);

  /**
   * Returns the value of the '<em><b>Level</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Level</em>' attribute list.
   * @see com.github.toerob.inform6.Inform6Package#getObjectDeclaration_Level()
   * @model unique="false"
   * @generated
   */
  EList<String> getLevel();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.github.toerob.inform6.Inform6Package#getObjectDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.ObjectDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Headline</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Headline</em>' attribute.
   * @see #setHeadline(String)
   * @see com.github.toerob.inform6.Inform6Package#getObjectDeclaration_Headline()
   * @model
   * @generated
   */
  String getHeadline();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.ObjectDeclaration#getHeadline <em>Headline</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Headline</em>' attribute.
   * @see #getHeadline()
   * @generated
   */
  void setHeadline(String value);

  /**
   * Returns the value of the '<em><b>In</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>In</em>' reference.
   * @see #setIn(ObjectDeclaration)
   * @see com.github.toerob.inform6.Inform6Package#getObjectDeclaration_In()
   * @model
   * @generated
   */
  ObjectDeclaration getIn();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.ObjectDeclaration#getIn <em>In</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>In</em>' reference.
   * @see #getIn()
   * @generated
   */
  void setIn(ObjectDeclaration value);

  /**
   * Returns the value of the '<em><b>Properties</b></em>' containment reference list.
   * The list contents are of type {@link org.eclipse.emf.ecore.EObject}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Properties</em>' containment reference list.
   * @see com.github.toerob.inform6.Inform6Package#getObjectDeclaration_Properties()
   * @model containment="true"
   * @generated
   */
  EList<EObject> getProperties();

} // ObjectDeclaration
