/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Property Directive</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.PropertyDirective#isAdditive <em>Additive</em>}</li>
 *   <li>{@link com.github.toerob.inform6.PropertyDirective#getName <em>Name</em>}</li>
 *   <li>{@link com.github.toerob.inform6.PropertyDirective#isAlias <em>Alias</em>}</li>
 *   <li>{@link com.github.toerob.inform6.PropertyDirective#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getPropertyDirective()
 * @model
 * @generated
 */
public interface PropertyDirective extends EObject
{
  /**
   * Returns the value of the '<em><b>Additive</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additive</em>' attribute.
   * @see #setAdditive(boolean)
   * @see com.github.toerob.inform6.Inform6Package#getPropertyDirective_Additive()
   * @model
   * @generated
   */
  boolean isAdditive();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.PropertyDirective#isAdditive <em>Additive</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additive</em>' attribute.
   * @see #isAdditive()
   * @generated
   */
  void setAdditive(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.github.toerob.inform6.Inform6Package#getPropertyDirective_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.PropertyDirective#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Alias</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Alias</em>' attribute.
   * @see #setAlias(boolean)
   * @see com.github.toerob.inform6.Inform6Package#getPropertyDirective_Alias()
   * @model
   * @generated
   */
  boolean isAlias();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.PropertyDirective#isAlias <em>Alias</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Alias</em>' attribute.
   * @see #isAlias()
   * @generated
   */
  void setAlias(boolean value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(Primary)
   * @see com.github.toerob.inform6.Inform6Package#getPropertyDirective_Value()
   * @model containment="true"
   * @generated
   */
  Primary getValue();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.PropertyDirective#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(Primary value);

} // PropertyDirective
