/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>STRING ARRAY</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.STRING_ARRAY#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getSTRING_ARRAY()
 * @model
 * @generated
 */
public interface STRING_ARRAY extends ArrayType
{
  /**
   * Returns the value of the '<em><b>Content</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' attribute list.
   * @see com.github.toerob.inform6.Inform6Package#getSTRING_ARRAY_Content()
   * @model unique="false"
   * @generated
   */
  EList<String> getContent();

} // STRING_ARRAY
