/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>TABLE ARRAY</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.TABLE_ARRAY#getSize <em>Size</em>}</li>
 *   <li>{@link com.github.toerob.inform6.TABLE_ARRAY#getContent <em>Content</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getTABLE_ARRAY()
 * @model
 * @generated
 */
public interface TABLE_ARRAY extends ArrayType
{
  /**
   * Returns the value of the '<em><b>Size</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Size</em>' containment reference.
   * @see #setSize(Primary)
   * @see com.github.toerob.inform6.Inform6Package#getTABLE_ARRAY_Size()
   * @model containment="true"
   * @generated
   */
  Primary getSize();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.TABLE_ARRAY#getSize <em>Size</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Size</em>' containment reference.
   * @see #getSize()
   * @generated
   */
  void setSize(Primary value);

  /**
   * Returns the value of the '<em><b>Content</b></em>' containment reference list.
   * The list contents are of type {@link com.github.toerob.inform6.Primary}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Content</em>' containment reference list.
   * @see com.github.toerob.inform6.Inform6Package#getTABLE_ARRAY_Content()
   * @model containment="true"
   * @generated
   */
  EList<Primary> getContent();

} // TABLE_ARRAY
