/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb Assignment</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see com.github.toerob.inform6.Inform6Package#getVerbAssignment()
 * @model
 * @generated
 */
public interface VerbAssignment extends EObject
{
} // VerbAssignment
