/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.VerbBody#getDefinitions <em>Definitions</em>}</li>
 *   <li>{@link com.github.toerob.inform6.VerbBody#getName <em>Name</em>}</li>
 *   <li>{@link com.github.toerob.inform6.VerbBody#getReverse <em>Reverse</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getVerbBody()
 * @model
 * @generated
 */
public interface VerbBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Definitions</b></em>' containment reference list.
   * The list contents are of type {@link com.github.toerob.inform6.VerbAssignment}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Definitions</em>' containment reference list.
   * @see com.github.toerob.inform6.Inform6Package#getVerbBody_Definitions()
   * @model containment="true"
   * @generated
   */
  EList<VerbAssignment> getDefinitions();

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.github.toerob.inform6.Inform6Package#getVerbBody_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.VerbBody#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Reverse</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Reverse</em>' attribute.
   * @see #setReverse(String)
   * @see com.github.toerob.inform6.Inform6Package#getVerbBody_Reverse()
   * @model
   * @generated
   */
  String getReverse();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.VerbBody#getReverse <em>Reverse</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Reverse</em>' attribute.
   * @see #getReverse()
   * @generated
   */
  void setReverse(String value);

} // VerbBody
