/**
 * generated by Xtext 2.22.0
 */
package com.github.toerob.inform6;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Verb Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link com.github.toerob.inform6.VerbDeclaration#getName <em>Name</em>}</li>
 *   <li>{@link com.github.toerob.inform6.VerbDeclaration#getMeta <em>Meta</em>}</li>
 *   <li>{@link com.github.toerob.inform6.VerbDeclaration#getSyn <em>Syn</em>}</li>
 *   <li>{@link com.github.toerob.inform6.VerbDeclaration#getDefintions <em>Defintions</em>}</li>
 *   <li>{@link com.github.toerob.inform6.VerbDeclaration#getOnly <em>Only</em>}</li>
 * </ul>
 *
 * @see com.github.toerob.inform6.Inform6Package#getVerbDeclaration()
 * @model
 * @generated
 */
public interface VerbDeclaration extends Directive
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see com.github.toerob.inform6.Inform6Package#getVerbDeclaration_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.VerbDeclaration#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Meta</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Meta</em>' attribute.
   * @see #setMeta(String)
   * @see com.github.toerob.inform6.Inform6Package#getVerbDeclaration_Meta()
   * @model
   * @generated
   */
  String getMeta();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.VerbDeclaration#getMeta <em>Meta</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Meta</em>' attribute.
   * @see #getMeta()
   * @generated
   */
  void setMeta(String value);

  /**
   * Returns the value of the '<em><b>Syn</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Syn</em>' attribute list.
   * @see com.github.toerob.inform6.Inform6Package#getVerbDeclaration_Syn()
   * @model unique="false"
   * @generated
   */
  EList<String> getSyn();

  /**
   * Returns the value of the '<em><b>Defintions</b></em>' containment reference list.
   * The list contents are of type {@link com.github.toerob.inform6.VerbBody}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Defintions</em>' containment reference list.
   * @see com.github.toerob.inform6.Inform6Package#getVerbDeclaration_Defintions()
   * @model containment="true"
   * @generated
   */
  EList<VerbBody> getDefintions();

  /**
   * Returns the value of the '<em><b>Only</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Only</em>' attribute.
   * @see #setOnly(String)
   * @see com.github.toerob.inform6.Inform6Package#getVerbDeclaration_Only()
   * @model
   * @generated
   */
  String getOnly();

  /**
   * Sets the value of the '{@link com.github.toerob.inform6.VerbDeclaration#getOnly <em>Only</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Only</em>' attribute.
   * @see #getOnly()
   * @generated
   */
  void setOnly(String value);

} // VerbDeclaration
